version: "3.7"
services:
  delta-postgres:
    build: postgres
    environment:
      - POSTGRES_PASSWORD=${DELTA_PG_ROOT_PASSWORD}
      - POSTGRES_DELTA_PASSWORD=${DELTA_PG_PASSWORD}
    networks:
      - default
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:4.28
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - default
      - hydra
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmindata:/usr/lib/pgadmin

  hydra:
    image: oryd/hydra:v1.9.0
    environment:
      - DSN=postgres://${HYDRA_PG_USERNAME}:${HYDRA_PG_PASSWORD}@hydra-postgres:5432/${HYDRA_PG_DATABASE}?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=adfogi7h4o83uignsleht438gzusidgh8s74hgizsd
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_SELF_PUBLIC=http://localhost:4444
      - URLS_LOGIN=http://localhost:3000/login
      - URLS_CONSENT=http://localhost:3000/consent
      - URLS_LOGOUT=http://localhost:3000/logout
      - URLS_ERROR=http://localhost:3000/error
      - URLS_POST_LOGOUT_REDIRECT=http://localhost:3000/post-login-redirect
    networks:
      - hydra
    ports:
      - 4444:4444 # Public port
      - 4445:4445 # Admin port
      - 5555:5555 # Port for hydra token user
    command: serve all --dangerous-force-http

  hydra-migrate:
    image: oryd/hydra:v1.9.0
    environment:
      - DSN=postgres://${HYDRA_PG_USERNAME}:${HYDRA_PG_PASSWORD}@hydra-postgres:5432/${HYDRA_PG_DATABASE}?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - hydra
    command: migrate sql -e --yes

  hydra-postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=${HYDRA_PG_DATABASE}
      - POSTGRES_USER=${HYDRA_PG_USERNAME}
      - POSTGRES_PASSWORD=${HYDRA_PG_PASSWORD}
    networks:
      - hydra

networks:
  default:
  hydra:

volumes:
  pgadmindata:
